[package]
name = "decent-profile-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
yew-router = "0.16.0"
stylist = { version = "0.10.0", features = ["yew"] }
gloo-utils = "0.1.2"
