[package]
name = "profile-viewer-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.12"
futures = "0.3.24"
reqwest = { version = "0.11.11", features = ["rustls-tls"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.88"
tokio = { version = "1.21.1", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = { version="0.3.15", features = ["env-filter"] }
