[package]
name = "profile-viewer-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.17"
futures = "0.3.28"
reqwest = { version = "0.11.13", features = ["rustls-tls"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version="0.3.15", features = ["env-filter"] }
