name: Apply Terraform [prd]

on:
  workflow_call:
    secrets:
      gcp_creds:
        required: true

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          ref: infra-prd

      - uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_creds }}"

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform
        run: |
          terraform init
          terraform plan -no-color -var-file="prd.tfvars.json"
          terraform apply -auto-approve -var-file="prd.tfvars.json"
