name: CI for web

on:
  push:
    branches:
      - "main"

env:
  RUST_VERSION: "1.59.0"
  TRUNK_VERSION: "0.14.0"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "${{ env.RUST_VERSION }}"
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true

      - uses: actions/cache@v2
        with:
          path: /home/runner/.cargo/bin/trunk
          key: "${{ runner.os }}-${{ env.RUST_VERSION }}-trunk-${{ env.TRUNK_VERSION }}"

      - name: Check trunk binary
        id: file_existence
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "/home/runner/.cargo/bin/trunk"

      - name: Install trunk
        run: "cargo install trunk --version $TRUNK_VERSION"
        if: steps.file_existence.outputs.files_exists != 'true'

      - run: trunk --version
