name: CI for web

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59.0
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true

      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.cargo/bin/trunk
          key: ${{ runner.os }}-1.59.0-trunk-0.14.0

      - name: Check trunk binary
        id: file_existence
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "/home/runner/.cargo/bin/trunk"

      - run: cargo install trunk
        if: steps.file_existence.outputs.files_exists != 'true'

      - run: trunk --version
