name: Check Terraform files

on:
  push:
    branches:
      - "main"
    paths:
      - terraform/**
      - .github/workflows/check-infra.yml

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Validate
        run: terraform validate -no-color
