name: CI for web

on:
  push:
    branches:
      - "main"
    paths:
      - web/**

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59.0
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true

      - uses: actions-rs/install@v0.1
        with:
          crate: trunk
          version: latest

      - uses: Swatinem/rust-cache@v1

      - name: Put dummy profile
        run: mkdir profiles && touch dummy.tcl

      - name: Check
        run: |
          cargo fmt --check
          cargo check
          cargo clippy

      - name: Build
        run: trunk build --release
