name: CI for backend

on:
  push:
    branches:
      - "main"
    paths:
      - backend/**

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check
        run: |
          cargo check
          cargo clippy

      - name: Build
        run: cargo build --release
