name: CI for backend

on:
  push:
    branches:
      - "main"
    paths:
      - backend/**
      - .github/workflows/check-backend.yml

env:
  RUST_VERSION: "1.59.0"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "${{ env.RUST_VERSION }}"
          components: rustfmt, clippy
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: |
          cargo fmt --check
          cargo check
          cargo clippy

      - name: Build
        run: cargo build --release
