name: Check Terraform files

on:
  push:
    branches:
      - "main"
    paths:
      - terraform/**

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Validate
        run: terraform validate -no-color
