name: Deploy infra [prd]

on:
  push:
    branches:
      - "infra-prd"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/apply-tf-prd.yml
