name: Deploy infra [prd]

on:
  push:
    branches:
      - "infra-prd"

jobs:
  deploy:
    name: Deploy Terraform [prd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # - uses: "google-github-actions/setup-gcloud@v0"

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve
