name: Deploy web [prd]

on:
  push:
    branches:
      - "web-prd"

env:
  RUST_VERSION: "1.59.0"
  TRUNK_VERSION: "0.14.0"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59.0
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v2

      - uses: actions/cache@v3
        with:
          path: /home/runner/.cargo/bin/trunk
          key: "${{ runner.os }}-${{ env.RUST_VERSION }}-trunk-${{ env.TRUNK_VERSION }}"

      - name: Check trunk binary
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "/home/runner/.cargo/bin/trunk"

      - name: Install trunk
        run: "cargo install trunk --version ${{ env.TRUNK_VERSION }}"
        if: steps.check_files.outputs.files_exists != 'true'

      - name: Build
        run: trunk build --release

      - name: Copy redirect file
        run: cp ./misc/netlify-redirects.txt ./dist/_redirects

      - name: Deploy to netlify
        run: npx netlify-cli deploy --dir=./dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
