name: Deploy backend [prd]

on:
  push:
    branches:
      - "backend-prd"

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Prepare variables
        id: vars
        run: echo "::set-output name=ga_commit_sha::${GITHUB_SHA::8}"

      - uses: "google-github-actions/setup-gcloud@v1"

      - name: Build and push to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          project_id: cropd-prj
          registry: gcr.io
          image_name: profile-viewer-api
          image_tag: ${{ steps.vars.outputs.ga_commit_sha }}
          dockerfile: backend/Dockerfile
          context: ./backend

  commit:
    name: Commit
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Prepare variables
        id: vars
        run: echo "::set-output name=ga_commit_sha::${GITHUB_SHA::8}"

      - name: Update tfvars file
        run: |
          cat terraform/prd.tfvars.json | jq '.backend.image_tag|="${{ steps.vars.outputs.ga_commit_sha }}"' -- > temp.json
          mv -f temp.json terraform/prd.tfvars.json
          cat terraform/prd.tfvars.json

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update to profile-viewer-api:${{ steps.vars.outputs.ga_commit_sha }} by GA"
          branch: infra-prd
          push_options: "--force"
          skip_checkout: true

  deploy:
    needs: commit
    uses: ./.github/workflows/apply-tf-prd.yml
    secrets:
      gcp_creds: ${{ secrets.GOOGLE_CREDENTIALS }}
