name: Deploy web [prd]

on:
  push:
    branches:
      - "web-prd"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59.0
          target: wasm32-unknown-unknown
          override: true

      - uses: actions-rs/install@v0.1.2
        with:
          crate: trunk
          version: latest
          use-tool-cache: true

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: trunk build --release

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Deploy to netlify
        run: npx netlify-cli deploy --dir=./dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
