name: Deploy infra [prd]

on:
  push:
    branches:
      - "infra-prd"

jobs:
  deploy:
    name: Deploy Terraform [prd]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v2

      - uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform
        run: |
          terraform init
          terraform plan -no-color
          terraform apply -auto-approve
