name: Deploy infra [prd]

on:
  push:
    branches:
      - "infra-prd"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: "google-github-actions/auth@v0"
        id: "auth"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - uses: "google-github-actions/setup-gcloud@v0"

      - run: "gcloud info"

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/infra-prd' && github.event_name == 'push'
        run: terraform apply -auto-approve
