name: Deploy infra [prd]

on:
  push:
    branches:
      - "infra-prd"

jobs:
  deploy:
    uses: ./.github/workflows/apply-tf-prd.yml
    secrets:
      gcp_creds: ${{ secrets.GOOGLE_CREDENTIALS }}
